# Generated by cucumber-sinatra. (2014-05-08 11:44:14 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', './server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = MyApp

class MyAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MyAppWorld.new
end


require 'database_cleaner'

DatabaseCleaner.strategy = :truncation

	Before do 
  	DatabaseCleaner.start
  end

  After do 
  	DatabaseCleaner.clean
  end